name: PR Check

on:
  push:
    branches:
      - feature/*
      - fix/*
      - dev/*

jobs:
  dockerfile_lint:
    runs-on: ubuntu-22.04
    container:
      image: hadolint/hadolint:v2.12.0-alpine
    env:
      DOCKERFILE_PATH: "Dockerfile"
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check Dockerfile Lint
      run: |
        hadolint ${DOCKERFILE_PATH}

  sh_lint:
    runs-on: ubuntu-22.04
    container:
      image: koalaman/shellcheck:v0.10.0
    env:
      SCRIPTS_PATH: "Scripts"
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check Scripts
      uses: ${SCRIPTS_PATH}/*.sh